[package]
name = "vm_boxed_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lasso = "0.6.0"
vm_codegen = { path = "../vm_codegen" }
vm_types = { path = "../vm_types" }
